branch-defaults:
  master:
    environment: dev-socketIO
global:
  application_name: Socket IO
  default_ec2_keyname: Terry-Laptop
  default_platform: 64bit Amazon Linux 2015.03 v1.3.0 running Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git