branch-defaults:
  dev:
    environment: dev-socketIO
  master:
    environment: dev-socketIO
global:
  application_name: Socket IO
  default_ec2_keyname: Terry-Laptop
  default_platform: Node.js
  default_region: null
  profile: null
  sc: git
